# Generated by Django 5.2.6 on 2025-10-03 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceLocation',
        ),
    ]
